# Generated by Django 4.1.1 on 2022-09-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='mostviewed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='newpost',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='trendsongs',
            field=models.BooleanField(default=True),
        ),
    ]
