# Generated by Django 4.1.1 on 2022-09-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blog_post_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='featured',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='mostviewed',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='newpost',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='trendsongs',
            field=models.BooleanField(),
        ),
    ]
