# Generated by Django 4.1.1 on 2022-09-12 12:48

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_blog_post_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='postbody',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='a'),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
