# Generated by Django 4.1.1 on 2022-09-12 12:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_blog_post_postbody_alter_blog_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='postbody',
            field=ckeditor.fields.RichTextField(default='a'),
        ),
    ]
