# Generated by Django 4.1.1 on 2022-09-12 12:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_blog_post_postbody'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='postbody',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
