# Generated by Django 4.1.1 on 2022-09-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_blog_post_postbody'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
